name: mve_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  delayed_display: ^2.0.0
  like_button: ^2.0.2
  story_view: ^0.16.5
  font_awesome_flutter: ^9.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/profil/
    - assets/image/post/
    - assets/image/video/
    - assets/image/photo/